/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_CCodeJni */

#ifndef _Included_com_microsoft_CCodeJni
#define _Included_com_microsoft_CCodeJni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_microsoft_CCodeJni_generateLowMemory (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
